# Meta info of the config
checkpoint:
model_name:
decoder_only:

cache_dir: .cache

hyperparams:
  group_1:
    lr:
    batch_size:
  group_2:
    lr:
    batch_size:
  group_3:
    lr:
    batch_size:

